changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: 'Breaking Changes 🔨'
      labels:
      - 'breaking-change'
    - title: 'Exciting New Features 🎉'
      labels:
      - 'feature'
    - title: 'Bug Fixes 🐛'
      labels:
      - 'bug'
    - title: 'Test 🧪'
      labels:
      - 'test'
    - title: 'Refactoring 🏭'
      labels:
      - 'refactoring'
    - title: 'Documentation 📖'
      labels:
      - 'documentation'
    - title: 'Dependency Updates 📦'
      labels:
      - 'dependencies'
    - title: Other Changes
      labels:
        - "*"
